version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ec-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: KEN_Interior_Shop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
